name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
    pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'


jobs:
  build-test-scan:
    name: CI - Build, Lint, Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: frontend

    - name: Lint code
      run: |
        npm install eslint --save-dev
        npx eslint .
      working-directory: frontend

    - name: Build React app
      run: npm run build
      working-directory: frontend

    - name: Run security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: weather_frontend:latest
        format: table
        severity: HIGH,CRITICAL

    - name: Build Docker image
      run: docker build -t weather_frontend ./frontend

  tag-and-push:
    name: CD - Tag and Push to Docker Hub
    needs: build-test-scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version tag
      run: echo "VERSION=v1.0.0-$(date +'%Y.%m.%d')-${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Build and tag image
      run: |
        docker build -t amara3000/weather_frontend:${{ env.VERSION }} ./frontend
        docker tag amara3000/weather_frontend:${{ env.VERSION }} amara3000/weather_frontend:latest

    - name: Push image to Docker Hub
      run: |
        docker push amara3000/weather_frontend:${{ env.VERSION }}
        docker push amara3000/weather_frontend:latest