name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/cicd_frontend.yaml'
  pull_request:
    branches: [ master ]
    paths:
       - 'frontend/**'
       - '.github/workflows/cicd_frontend.yaml'
  workflow_dispatch:

jobs:
  build-test-scan:
    name: CI - Build, Lint, Scan
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.VERSION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: frontend

    - name: Run audit and allow warnings
      run: |
        npm audit || echo "Audit completed with vulnerabilities"
      working-directory: frontend


    - name: Update Browserslist DB
      run: npx update-browserslist-db@latest
      working-directory: frontend

    - name: Lint code
      run: |
        npm install eslint --save-dev
        npx eslint src
      working-directory: frontend

    - name: Build React app
      run: npm run build
      working-directory: frontend

    - name: Extract version tag
      id: version
      run: echo "VERSION=v1.0.0-$(date +'%Y.%m.%d')-${GITHUB_SHA}" >> $GITHUB_ENV && echo "VERSION=v1.0.0-$(date +'%Y.%m.%d')-${GITHUB_SHA}" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build -t amara3000/weather_frontend:${{ env.VERSION }} ./frontend

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to Docker Hub
      run: docker push amara3000/weather_frontend:${{ env.VERSION }}

    - name: Run security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: amara3000/weather_frontend:${{ env.VERSION }}
        format: table
        severity: HIGH,CRITICAL

  tag-and-push:
    name: CD - Tag and Push to Docker Hub
    needs: build-test-scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull versioned image
      run: docker pull amara3000/weather_frontend:${{ needs.build-test-scan.outputs.version }}

    - name: Tag image
      run: |
        docker tag amara3000/weather_frontend:${{ needs.build-test-scan.outputs.version }} amara3000/weather_frontend:latest

    - name: Push image to Docker Hub
      run: |
        docker push amara3000/weather_frontend:${{ needs.build-test-scan.outputs.version }}
        docker push amara3000/weather_frontend:latest